{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Финальный проект\n",
    "\n",
    "### Запуск\n",
    "\n",
    "Для запуска потребуется установить две библиотеки, оно того стоит, правда.  \n",
    "Для этого необходимо последовательно запустить две следующие ячейки и надеяться на лучшее.\n",
    "\n",
    "Если вы выдержили это — спасибо!\n",
    "Кстати, теперь у вас работает отличная библиотека, которая запросто строит вордклауды из любого текста, который даже не нужно предобрабатывать."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# Раз\n",
    "\n",
    "! conda install -c conda-forge wordcloud --y"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# Два\n",
    "\n",
    "! conda install -c c3i_test2 pillow --y"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Описание\n",
    "\n",
    "1. Программа обращается к API правительства РФ и запрашивает данные о депутатах ГД и СФ.\n",
    "2. Все депутаты отсортировываются по палатам парламента, фракциям и статусу действующий депутат/недействующий\n",
    "4. При сортировке используются регулярные выражения, и функции pandas\n",
    "5. На бэкенде генерируются страницы сайта\n",
    "6. При открытии страницы депутата, с API запрашиваются данные о депутате и стенограммы протоколов заседаний в которых он участвовал, если данная информация доступна программа генерирует страницу депутата с вордслаудами создаными на основании речей депутата, разбитыми по годам (pandas)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [09/Jul/2018 03:55:37] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [09/Jul/2018 03:55:37] \"GET /static/Duma_style.css HTTP/1.1\" 200 -\n",
      "[2018-07-09 03:55:38,960] ERROR in app: Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 161, in show_team\n",
      "    data = get_team(df, team)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 55, in get_team\n",
      "    team_slice = df['position'] == names[team]\n",
      "KeyError: 'favicon.ico'\n",
      "127.0.0.1 - - [09/Jul/2018 03:55:39] \"GET /favicon.ico HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [09/Jul/2018 03:57:13] \"GET /faction/72100018 HTTP/1.1\" 200 -\n",
      "[2018-07-09 03:57:13,270] ERROR in app: Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 161, in show_team\n",
      "    data = get_team(df, team)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 55, in get_team\n",
      "    team_slice = df['position'] == names[team]\n",
      "KeyError: 'favicon.ico'\n",
      "127.0.0.1 - - [09/Jul/2018 03:57:13] \"GET /favicon.ico HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [09/Jul/2018 03:57:16] \"GET / HTTP/1.1\" 200 -\n",
      "[2018-07-09 03:57:16,861] ERROR in app: Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 161, in show_team\n",
      "    data = get_team(df, team)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 55, in get_team\n",
      "    team_slice = df['position'] == names[team]\n",
      "KeyError: 'favicon.ico'\n",
      "127.0.0.1 - - [09/Jul/2018 03:57:16] \"GET /favicon.ico HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [09/Jul/2018 03:57:18] \"GET /faction/72100002 HTTP/1.1\" 200 -\n",
      "[2018-07-09 03:57:19,061] ERROR in app: Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 161, in show_team\n",
      "    data = get_team(df, team)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 55, in get_team\n",
      "    team_slice = df['position'] == names[team]\n",
      "KeyError: 'favicon.ico'\n",
      "127.0.0.1 - - [09/Jul/2018 03:57:19] \"GET /favicon.ico HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [09/Jul/2018 03:57:22] \"GET / HTTP/1.1\" 200 -\n",
      "[2018-07-09 03:57:23,132] ERROR in app: Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 161, in show_team\n",
      "    data = get_team(df, team)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 55, in get_team\n",
      "    team_slice = df['position'] == names[team]\n",
      "KeyError: 'favicon.ico'\n",
      "127.0.0.1 - - [09/Jul/2018 03:57:23] \"GET /favicon.ico HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [09/Jul/2018 03:57:26] \"GET /SF HTTP/1.1\" 200 -\n",
      "[2018-07-09 03:57:27,112] ERROR in app: Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 161, in show_team\n",
      "    data = get_team(df, team)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 55, in get_team\n",
      "    team_slice = df['position'] == names[team]\n",
      "KeyError: 'favicon.ico'\n",
      "127.0.0.1 - - [09/Jul/2018 03:57:27] \"GET /favicon.ico HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [09/Jul/2018 03:57:33] \"GET /GD HTTP/1.1\" 200 -\n",
      "[2018-07-09 03:57:33,914] ERROR in app: Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 161, in show_team\n",
      "    data = get_team(df, team)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 55, in get_team\n",
      "    team_slice = df['position'] == names[team]\n",
      "KeyError: 'favicon.ico'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [09/Jul/2018 03:57:33] \"GET /favicon.ico HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [09/Jul/2018 03:57:40] \"GET / HTTP/1.1\" 200 -\n",
      "[2018-07-09 03:57:41,336] ERROR in app: Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 161, in show_team\n",
      "    data = get_team(df, team)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 55, in get_team\n",
      "    team_slice = df['position'] == names[team]\n",
      "KeyError: 'favicon.ico'\n",
      "127.0.0.1 - - [09/Jul/2018 03:57:41] \"GET /favicon.ico HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [09/Jul/2018 03:58:05] \"GET /deputat/99112511 HTTP/1.1\" 200 -\n",
      "[2018-07-09 03:58:05,673] ERROR in app: Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 161, in show_team\n",
      "    data = get_team(df, team)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 55, in get_team\n",
      "    team_slice = df['position'] == names[team]\n",
      "KeyError: 'favicon.ico'\n",
      "127.0.0.1 - - [09/Jul/2018 03:58:05] \"GET /favicon.ico HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [09/Jul/2018 04:00:56] \"GET / HTTP/1.1\" 200 -\n",
      "[2018-07-09 04:00:57,372] ERROR in app: Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 161, in show_team\n",
      "    data = get_team(df, team)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 55, in get_team\n",
      "    team_slice = df['position'] == names[team]\n",
      "KeyError: 'favicon.ico'\n",
      "127.0.0.1 - - [09/Jul/2018 04:00:57] \"GET /favicon.ico HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [09/Jul/2018 04:01:15] \"GET /deputat/99109998 HTTP/1.1\" 200 -\n",
      "[2018-07-09 04:01:15,594] ERROR in app: Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 161, in show_team\n",
      "    data = get_team(df, team)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 55, in get_team\n",
      "    team_slice = df['position'] == names[team]\n",
      "KeyError: 'favicon.ico'\n",
      "127.0.0.1 - - [09/Jul/2018 04:01:15] \"GET /favicon.ico HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [09/Jul/2018 04:01:41] \"GET / HTTP/1.1\" 200 -\n",
      "[2018-07-09 04:01:41,762] ERROR in app: Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 161, in show_team\n",
      "    data = get_team(df, team)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 55, in get_team\n",
      "    team_slice = df['position'] == names[team]\n",
      "KeyError: 'favicon.ico'\n",
      "127.0.0.1 - - [09/Jul/2018 04:01:41] \"GET /favicon.ico HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [09/Jul/2018 04:02:06] \"GET /deputat/99100289 HTTP/1.1\" 200 -\n",
      "[2018-07-09 04:02:06,891] ERROR in app: Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 161, in show_team\n",
      "    data = get_team(df, team)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 55, in get_team\n",
      "    team_slice = df['position'] == names[team]\n",
      "KeyError: 'favicon.ico'\n",
      "127.0.0.1 - - [09/Jul/2018 04:02:06] \"GET /favicon.ico HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [09/Jul/2018 04:02:11] \"GET / HTTP/1.1\" 200 -\n",
      "[2018-07-09 04:02:11,630] ERROR in app: Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 161, in show_team\n",
      "    data = get_team(df, team)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 55, in get_team\n",
      "    team_slice = df['position'] == names[team]\n",
      "KeyError: 'favicon.ico'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [09/Jul/2018 04:02:11] \"GET /favicon.ico HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [09/Jul/2018 04:02:45] \"GET /deputat/99100543 HTTP/1.1\" 200 -\n",
      "[2018-07-09 04:02:46,067] ERROR in app: Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\artuo\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 161, in show_team\n",
      "    data = get_team(df, team)\n",
      "  File \"<ipython-input-1-c8195f354f3d>\", line 55, in get_team\n",
      "    team_slice = df['position'] == names[team]\n",
      "KeyError: 'favicon.ico'\n",
      "127.0.0.1 - - [09/Jul/2018 04:02:46] \"GET /favicon.ico HTTP/1.1\" 500 -\n"
     ]
    }
   ],
   "source": [
    "# Запуск тут, ссылка появится снизу. \n",
    "# ...ну, или ошибка.\n",
    "# если-таки выдаст ошибку попробуйте перезапустить юпитер (на маке бывало)\n",
    "\n",
    "import requests\n",
    "from flask import Flask, render_template\n",
    "import pandas as pd\n",
    "import re\n",
    "from datetime import datetime\n",
    "from wordcloud import WordCloud\n",
    "import base64\n",
    "from io import BytesIO\n",
    "\n",
    "app = Flask(__name__)\n",
    "app.debug = True\n",
    "\n",
    "main_url = 'http://api.duma.gov.ru/api/'\n",
    "my_token = '0fb77544c3c20cd24261b2302562091b44644913'\n",
    "my_app_token = 'app3831cc79355d162d0de8b34e68ec427c12f4cb27'\n",
    "\n",
    "prl = 'contprl'\n",
    "gd = 'contgd'\n",
    "sf = 'contsf'\n",
    "\n",
    "def get_data(mainurl, mytoken, myapptoken):\n",
    "\n",
    "    deputats_wet = requests.get(mainurl + mytoken +\n",
    "                                '/deputies.json?app_token=' +\n",
    "                                myapptoken).json()\n",
    "    deputats = []\n",
    "    for e in deputats_wet:\n",
    "        ee = dict((k, v) for k, v in e.items() if k != 'factions' and k != 'id')\n",
    "        if 'factions' in e and len(e['factions']) > 0:\n",
    "            fa = e['factions'][-1]['name']\n",
    "            fa_id = e['factions'][-1]['id']\n",
    "        else:\n",
    "            fa = 'Депутаты, не входящие во фракции'\n",
    "            fa_id = 99111552\n",
    "\n",
    "        ee['curr_last_faction'] = fa\n",
    "        ee['curr_last_faction_id'] = fa_id\n",
    "        ee['ind'] = e['id']\n",
    "        deputats.append(ee)\n",
    "    df = pd.DataFrame(deputats)\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "df  = get_data(main_url, my_token, my_app_token)\n",
    "\n",
    "\n",
    "def get_team(df, team):\n",
    "\n",
    "    names = {'GD' : 'Депутат ГД', 'SF' : 'Член СФ'}\n",
    "    team_slice = df['position'] == names[team]\n",
    "\n",
    "    return df[team_slice]\n",
    "\n",
    "\n",
    "def get_faction(df, faction):\n",
    "\n",
    "    faction_slice = df['curr_last_faction_id'] == str(faction)\n",
    "\n",
    "    return df[faction_slice]\n",
    "\n",
    "\n",
    "def fir(tou):\n",
    "    return tou[0]\n",
    "\n",
    "\n",
    "def parse_data(df):\n",
    "\n",
    "    fac = list(set(zip(list(df['curr_last_faction']),\n",
    "                       list(df['curr_last_faction_id']))))\n",
    "    fac = sorted(fac, key=fir)\n",
    "\n",
    "    tt = df['isCurrent'] == True\n",
    "    ff = df['isCurrent'] == False\n",
    "\n",
    "    curr_t = list(zip(list(df[tt]['name']),\n",
    "                      list(df[tt]['ind'])))\n",
    "    curr_t = sorted(curr_t, key=fir)\n",
    "    curr_f = list(zip(list(df[ff]['name']),\n",
    "                      list(df[ff]['ind'])))\n",
    "    curr_f = sorted(curr_f, key=fir)\n",
    "\n",
    "    return fac, curr_t, curr_f\n",
    "\n",
    "\n",
    "def get_dep(mainurl, mytoken, myapptoken, ind):\n",
    "\n",
    "    data = requests.get(mainurl + mytoken +\n",
    "                        '/deputy.json?app_token=' +\n",
    "                        myapptoken + '&id=' +\n",
    "                        str(ind)).json()\n",
    "\n",
    "    return data\n",
    "\n",
    "\n",
    "def get_text(mainurl, mytoken, myapptoken, ind):\n",
    "    url = (mainurl + mytoken +\n",
    "           '/transcriptDeputy/' +\n",
    "           str(ind) + '.json?app_token=' +\n",
    "           myapptoken +\n",
    "           '&limit=20&page=1')\n",
    "\n",
    "    rj = requests.get(url).json()\n",
    "\n",
    "    total = int(rj['totalCount'])\n",
    "    if total / 20 > total // 20:\n",
    "        num = total // 20 + 1\n",
    "    else:\n",
    "        num = total // 20\n",
    "\n",
    "    data = [rj]\n",
    "\n",
    "    for i in range(2, num + 1):\n",
    "        rjs = requests.get(url).json()\n",
    "        data.append(rjs)\n",
    "\n",
    "    return data\n",
    "\n",
    "\n",
    "def parse_text_data(textdata):\n",
    "    data = []\n",
    "    for td in textdata:\n",
    "        for e in td['meetings']:\n",
    "            cur_date = e['date']\n",
    "            que = len(e['questions'])\n",
    "            lines = []\n",
    "            for q in e['questions']:\n",
    "                for p in q['parts']:\n",
    "                    for ind, l in enumerate(p['lines']):\n",
    "                        if l.strip() == '':\n",
    "                            lines.extend(p['lines'][ind:])\n",
    "                            break\n",
    "\n",
    "            lines = [l.strip() for l in lines if l.strip() != '']\n",
    "            lines = ' '.join(lines).lower()\n",
    "\n",
    "            c = [cur_date, lines, que]\n",
    "            data.append(c)\n",
    "    return data\n",
    "\n",
    "\n",
    "@app.route('/')\n",
    "def show_duma():\n",
    "\n",
    "    fac, curr_t, curr_f, = parse_data(df)\n",
    "\n",
    "    return render_template(\"Duma_main.html\",\n",
    "                           fac = fac,\n",
    "                           curr_t = curr_t,\n",
    "                           curr_f = curr_f,\n",
    "                           sty = prl)\n",
    "\n",
    "\n",
    "@app.route(\"/<team>\")\n",
    "def show_team(team):\n",
    "\n",
    "    data = get_team(df, team)\n",
    "    fac, curr_t, curr_f, = parse_data(data)\n",
    "    if team == 'GD':\n",
    "        sty = gd\n",
    "    else:\n",
    "        sty = sf\n",
    "\n",
    "    return render_template(\"Duma_main.html\",\n",
    "                           fac = fac,\n",
    "                           curr_t = curr_t,\n",
    "                           curr_f = curr_f,\n",
    "                           sty = sty)\n",
    "\n",
    "\n",
    "@app.route(\"/faction/<int:faction>\")\n",
    "def show_faction(faction):\n",
    "\n",
    "    data = get_faction(df, faction)\n",
    "    fac, curr_t, curr_f = parse_data(data)\n",
    "\n",
    "    return render_template(\"Duma_main.html\",\n",
    "                           fac = fac,\n",
    "                           curr_t = curr_t,\n",
    "                           curr_f = curr_f,\n",
    "                           sty = prl)\n",
    "\n",
    "\n",
    "@app.route(\"/deputat/<int:index>\")\n",
    "def show_deputat(index):\n",
    "\n",
    "    data = get_dep(main_url, my_token,\n",
    "                   my_app_token, index)\n",
    "\n",
    "    if data:\n",
    "        name = data['name']\n",
    "        patronymic = data['patronymic']\n",
    "        family = data['family']\n",
    "        birthdate = data.get('birthdate', '—')\n",
    "        if birthdate != '—':\n",
    "            bd = datetime.strptime(birthdate, '%Y-%m-%d')\n",
    "            birthdate = bd.strftime('%d.%m.%Y')\n",
    "        credentialsStart = data.get('credentialsStart', '—')\n",
    "        if credentialsStart != '—':\n",
    "            sd = datetime.strptime(credentialsStart, '%Y-%m-%d')\n",
    "            credentialsStart = sd.strftime('%d.%m.%Y')\n",
    "        credentialsEnd = data.get('credentialsEnd', '—')\n",
    "        if credentialsEnd != '—':\n",
    "            ed = datetime.strptime(credentialsEnd, '%Y-%m-%d')\n",
    "            credentialsEnd = ed.strftime('%d.%m.%Y')\n",
    "        factionName = data.get('factionName', '—')\n",
    "        factionRole = data.get('factionRole', '—')\n",
    "        if factionRole != '—':\n",
    "            factionRole = re.sub(r'\\d+\\s\\b', r'', factionRole)\n",
    "        factionRegion = data.get('factionRegion', '—')\n",
    "        partyNameInstr = data.get('partyNameInstr', '—')\n",
    "        lawcount = data.get('lawcount', '—')\n",
    "        regions = data.get('regions', '—')\n",
    "\n",
    "        with open('stop_words.txt', 'r', encoding='utf-8') as f:\n",
    "            stopw = [e.strip() for e in f.readlines() if e.strip() != '']\n",
    "\n",
    "        td = get_text(main_url, my_token, my_app_token, index)\n",
    "        ff = parse_text_data(td)\n",
    "        df = pd.DataFrame(ff)\n",
    "        df = df.set_index(pd.to_datetime(df[0]))\n",
    "        dff = list(df.groupby([df.index.year]))\n",
    "        text_per_year = []\n",
    "        for e in dff:\n",
    "            y = e[0]\n",
    "            t = ' '.join(e[1][1])\n",
    "            q = sum(e[1][2])\n",
    "            c = (y, t, q)\n",
    "            text_per_year.append(c)\n",
    "        pics = []\n",
    "        wc = WordCloud(colormap='gist_heat', max_words=50, background_color='white',\n",
    "                       prefer_horizontal=1, width=1000, height=500, stopwords=stopw)\n",
    "        for text in text_per_year:\n",
    "            wc.generate(text[1])\n",
    "            v = wc.to_image()\n",
    "            figfile = BytesIO()\n",
    "            v.save(figfile, 'PNG')\n",
    "            figfile.seek(0)\n",
    "            figdata_png = base64.b64encode(figfile.getvalue())\n",
    "            result = str(figdata_png)[2:-1]\n",
    "            num_of_questions = text[2]\n",
    "            c = (text[0], result, num_of_questions)\n",
    "            pics.append(c)\n",
    "\n",
    "        return render_template(\"Deputat_page.html\",\n",
    "                               name=name,\n",
    "                               patronymic=patronymic,\n",
    "                               family=family,\n",
    "                               birthdate=birthdate,\n",
    "                               credentialsStart=credentialsStart,\n",
    "                               credentialsEnd=credentialsEnd,\n",
    "                               factionName=factionName,\n",
    "                               factionRole=factionRole,\n",
    "                               factionRegion=factionRegion,\n",
    "                               partyNameInstr=partyNameInstr,\n",
    "                               lawcount=lawcount,\n",
    "                               regions=regions,\n",
    "                               pics=pics)\n",
    "    else:\n",
    "        return render_template(\"No_page.html\")\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    app.run(debug=False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
